name: Version Bump merged

on: push

jobs:
  trigger-release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'bump_version_to_')
    environment: Create Release
    steps:
      - name: Get new version
        id: get-new-version
        run: |
          NEW_VERSION=$(echo ${{ github.event.head_commit.message }} | cut -d _ -f4 )
          echo "::set-output name=version::$NEW_VERSION"
      - name: Is prerelease?
        id: is-prerelease
        run: |
          IS_PRERELEASE=$([[ "${{ steps.get-new-version.outputs.version }}" == *-* ]] && echo true || echo false)
          echo "::set-output name=result::$IS_PRERELEASE"
      - name: Echo result
        run: |
          echo ${{ steps.get-new-version.outputs.version }}
          echo ${{ steps.is-prerelease.outputs.result }}
