name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - <<: *myTemplate

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - <<: *myTemplate

# Define the reusable steps as an anchor
myTemplate:
  - name: Step 1
    run: echo "Running step 1"

  - name: Step 2
    run: echo "Running step 2"

  - name: Step 3
    run: echo "Running step 3"

