name: PR Auto Update

on:
  pull_request:
    types: [opened]   # only when PR is created; you could also add "edited" if you want it to re-run

jobs:
  update-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Update PR title and body
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;

            // Example: prepend "[AUTO]" to the title
            const newTitle = `[AUTO] ${context.payload.pull_request.title}`;

            // Example: add a footer to the PR body
            const newBody = `
            ${context.payload.pull_request.body || ''}

            ---
            _This PR was auto-updated by a GitHub Action._
            `;

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              title: newTitle,
              body: newBody
            });
